<?php

namespace PeliculasBundle\Repository;

/**
 * GeneroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneroRepository extends \Doctrine\ORM\EntityRepository
{
}
